# http://module-build.sourceforge.net/META-spec.html
#
name:         Finance-Bank-DE-LBB-Creditcard
version:      0.1
version_from: Creditcard.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
